services:
  highway:
    build:
      context: .
      dockerfile: highway/Dockerfile
    container_name: backend_imm
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - "8888:8000"
      - "8678:5678"
    networks:
      - app-network
    restart: unless-stopped

  postgres:
    image: postgres:15
    container_name: postgres_imm
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - app-network
    ports:
      - "5432:5432"
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
