services:
  highway:
    build:
      context: ./highway
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql+asyncpg://immuser:immpass@postgres:5432/immersiadb
    ports:
      - "8888:8000"
      - "8678:5678"
    networks:
      - app-network
    restart: unless-stopped

  postgres:
    image: postgres:15
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: immersiadb
      POSTGRES_USER: immuser
      POSTGRES_PASSWORD: immpass
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
