services:
  highway:
    build:
      context: .
      dockerfile: highway/Dockerfile
    container_name: backend_imm
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    ports:
      - "8888:8000"
      - "8678:5678"
    networks:
      - app-network
    restart: unless-stopped

  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    container_name: bot_imm
    environment:
      - TG_BOT_TOKEN=${TG_BOT_TOKEN}
      - ADMIN_ID=${ADMIN_ID}
      - APP_URL=http://highway:8000
      - WEB_URL=${WEB_URL}
      - API_KEY=SECRET_TOKEN
    ports:
      - "25678:5678"
    networks:
      - app-network
    env_file:
      - .env
    depends_on:
      - highway
      - redis
    restart: unless-stopped

  postgres:
    image: postgres:15
    container_name: postgres_imm
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - app-network
    ports:
      - "5432:5432"
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: redis_imm
    networks:
      - app-network
    ports:
      - "6379:6379"
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
