"""new_migration

Revision ID: 922b6f6d0192
Revises: 1b2c3d4e5f6a
Create Date: 2025-08-02 14:26:48.370224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '922b6f6d0192'
down_revision: Union[str, Sequence[str], None] = '1b2c3d4e5f6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bundle_purchases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bundle', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('purchased_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('invoice_payload', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bundle_purchases_invoice_payload'), 'bundle_purchases', ['invoice_payload'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bundle_purchases_invoice_payload'), table_name='bundle_purchases')
    op.drop_table('bundle_purchases')
    # ### end Alembic commands ###
