"""add visual style to story

Revision ID: ad626564aa2f
Revises: f9ddc695d680
Create Date: 2025-08-03 18:38:56.203617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad626564aa2f'
down_revision: Union[str, Sequence[str], None] = 'f9ddc695d680'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stories', sa.Column('image_url', sa.Text(), nullable=True))
    op.add_column('stories', sa.Column('visual_style', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stories', 'visual_style')
    op.drop_column('stories', 'image_url')
    # ### end Alembic commands ###
