"""Pydantic models representing game state and LLM outputs."""

from typing import Dict, List, Optional, Set, Literal

from pydantic import BaseModel, Field


class Milestone(BaseModel):
    """Milestone that can be achieved during the story."""

    id: str
    description: str

class NPCCharacter(BaseModel):
    """NPC character."""

    char_name: str
    char_age: str
    char_background: str
    char_personality: str
    visual_description: str

class Ending(BaseModel):
    """Possible game ending."""

    id: str
    type: Literal["good", "neutral", "bad"]
    condition: str
    description: str = Field(
        description="Highly detailed description of the ending, it should contain at least 50 words."
    )


class StoryFrame(BaseModel):
    """Overall plot information generated by the LLM."""

    lore: str
    goal: str
    milestones: List[Milestone]
    endings: List[Ending]
    setting: str
    character: Dict[str, str]
    visual_style: str
    genre: str
    language: str = "en"
    npc_characters: List[NPCCharacter]


class StoryFrameLLM(BaseModel):
    """Structure returned by the LLM for story frame generation."""

    lore: str
    goal: str
    milestones: List[Milestone]
    endings: List[Ending]


class SceneChoice(BaseModel):
    """User choice leading to another scene."""

    text: str


class PlayerOption(BaseModel):
    """Option presented to the player in a scene."""

    option_description: str = Field(
        description=(
            "Description of the option, e.g. '[Say] Hello!' or "
            "'Go to the forest'"
        )
    )


class Scene(BaseModel):
    """Game scene with choices and optional assets."""

    scene_id: str
    description: str
    choices: List[SceneChoice]
    image: Optional[str] = None
    image_prompt: Optional[str] = None
    music: Optional[str] = None


class SceneLLM(BaseModel):
    """Structure expected from the LLM when generating a scene."""

    description: str
    choices: List[SceneChoice] = Field(min_items=2, max_items=2)


class EndingCheckResult(BaseModel):
    ending_reached: bool
    """If ending_reached is True, ending is not None"""
    ending: Optional[Ending] = None


class UserChoice(BaseModel):
    """Single player choice recorded in the history."""

    scene_id: str
    choice_text: str
    timestamp: Optional[str] = None


class UserState(BaseModel):
    """State stored for each user."""
    story_frame: Optional[StoryFrame] = None
    current_scene_id: Optional[str] = None
    scenes: Dict[str, Scene] = Field(default_factory=dict)
    milestones_achieved: Set[str] = Field(default_factory=set)
    user_choices: List[UserChoice] = Field(default_factory=list)
    ending: Optional[Ending] = None
    last_image_prompt: Optional[str] = None
    assets: Dict[str, str] = Field(default_factory=dict)
    language: str = "en"
    image_format: str = "vertical"
    is_pro: bool = False
